"""Build Bandu's public, dependency-free website."""
from pathlib import Path
from html import escape
import os

project = Path(__file__).resolve().parents[1]
root = project / ('server/site' if (project / 'server/site').exists() else 'site')
root.mkdir(parents=True, exist_ok=True)
email = os.environ.get('BANDU_PUBLIC_SUPPORT_EMAIL', 'gobacktome123@gmail.com')
contact = ('<a href="mailto:' + escape(email, quote=True) + '">' + escape(email) + '</a>') if email else '试用用户请联系向你提供邀请码的人员。公开客服邮箱配置中。'
nav = '<header><a class="brand" href="/"><b>伴</b> 伴读 <span>Bandu</span></a><nav><a href="/#how">使用方式</a><a href="/api.html">API 设置</a><a href="/support.html">帮助</a><a class="login" href="https://github.com/polytradingwin/bandu">GitHub ↗</a></nav></header>'
footer = '<footer><a class="brand" href="/">伴读 Bandu</a><p>由 Nexwave International Limited 运营</p><div><a href="/about.html">公司信息</a><a href="/privacy.html">隐私政策</a><a href="/terms.html">服务条款</a><a href="/refunds.html">历史订单</a><a href="/support.html">联系我们</a></div><small>© 2026 Nexwave International Limited</small></footer>'
def write(name, title, body, article=False):
    canonical = 'https://bandume.com/' + ('' if name == 'index.html' else name)
    html = f'<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="伴读 Bandu：保留英文原文的网页双语阅读扩展。免费开源，自带 API Key。安装、配置和隐私说明。"><title>{title} · 伴读 Bandu</title><link rel="canonical" href="{canonical}"><link rel="stylesheet" href="/site.css"></head><body>{nav}<main class="{"article" if article else "home"}">{body}</main>{footer}</body></html>'
    html = html.replace('</head>', '<link rel="icon" type="image/png" href="/favicon.png"></head>')
    (root / name).write_text(html, encoding='utf-8')


write('index.html', '免费开源，自带 API', '<section class="hero"><div><p class="eyebrow">伴读 BANDU / 免费 · 开源</p><h1>读懂这一句。<br><em>继续读下去。</em></h1><p class="lead">英文留在原处，中文紧随其后。<br>用你自己的 API，让理解跟上好奇心。</p><div class="actions"><a class="button" href="/install.html">免费安装伴读</a><a href="https://github.com/polytradingwin/bandu">查看开源代码 ↗</a></div><p class="muted">无需注册伴读账号 · 无会员费 · API 费用由服务商收取</p></div><div class="reading"><div class="reading-top">READING WITH BANDU <span>双语阅读示例</span></div><p class="original">You don’t have to understand every word to enjoy the story.</p><p class="translation">不必弄懂每一个词，也能享受故事的乐趣。</p><p class="original second">Keep reading. The meaning will come into focus.</p><p class="translation">继续读下去，意思会慢慢清晰。</p><p class="note">排版与译文示意，非实时翻译</p></div></section>\n<section id="how" class="how"><p class="eyebrow">三步，开始双语阅读</p><h2>在你正在看的网页上，<br>多一行理解。</h2><div class="steps"><div><span>01 / 安装</span><h3>把伴读装进浏览器</h3><p>支持电脑 Chrome / Edge，英文原文与网页操作保持完整。</p></div><div><span>02 / 配置</span><h3>选择你自己的 API</h3><p>填入自己的密钥和模型，测试并启用。无需购买伴读会员。</p></div><div><span>03 / 阅读</span><h3>原文与译文对照着读</h3><p>X 默认开启；其他网站点击伴读开关并授权。宽屏左右，窄屏上下。</p></div></div></section>\n<section class="plans"><div><p class="eyebrow">你的服务商，你来选择</p><h2>伴读免费。<br>API 自带。</h2><p>支持 OpenAI、Claude、Gemini、DeepSeek、千问、Kimi、GLM、豆包、硅基流动等常见平台，以及自定义兼容接口、Ollama 和 LM Studio。</p><p>密钥仅保存在浏览器，待译正文直接发往你配置的 API 地址。伴读不提供公共额度，不代收模型费用。</p></div><div class="trial"><div><strong>¥0</strong><span>伴读软件费用</span></div><p>MIT 开源，无会员、无软件付费墙。第三方 API 的用量、价格及可用性由各服务商决定。</p><a class="button" href="/api.html">查看 API 配置指南 ↗</a></div></section>\n<section class="faq"><p class="eyebrow">开始之前</p><h2>你可能想了解</h2><details><summary>为什么还要填写 API Key？</summary><p>伴读负责网页提取与双语排版，模型翻译由你选择的 API 提供。软件免费不代表服务商 API 免费。聊天会员通常不含 API 额度。</p></details><details><summary>官网还需要注册或付费吗？</summary><p>不需要。官网提供安装、说明和开源链接。旧会员已停止新售卖，历史订单可联系支持查询。</p></details><details><summary>哪些设备可以用？</summary><p>Windows / macOS 的 Chrome 和 Edge。当前未提供 Safari、iPad 或 Android 正式版，不支持 PDF、图片文字或浏览器内部页面。</p></details><details><summary>EngBetter 必须连接吗？</summary><p>无需连接。它是独立的可选收藏服务，只在你主动连接并收藏时接收所选内容。</p></details></section>')
write('install.html','安装伴读', '<p class="eyebrow">GET STARTED / 1.0.0</p><h1>免费安装，配置自己的 API。</h1><p><a class="button" href="https://chromewebstore.google.com/detail/ojkjhponlgoeagionaepmkjnkifnoiho" target="_blank" rel="noreferrer">Chrome 应用商店 ↗</a></p><p>免费自备 API 版为 1.0.0。商店更新需要审核，如果商店仍是旧会员版，请使用下方 GitHub 下载，不必购买会员。</p><p><a href="https://github.com/polytradingwin/bandu/releases/latest">下载最新免费版 ZIP ↗</a> · <a href="https://github.com/polytradingwin/bandu">查看源码</a></p><ol><li>下载手动安装包并解压到固定目录。</li><li>打开 chrome://extensions 或 edge://extensions，开启开发者模式，点击“加载已解压的扩展程序”，选择 extension 文件夹。</li><li>固定伴读到工具栏。在 API 设置页选择服务商，填写自己的 API Key、模型和地址，测试并启用。</li><li>打开英文网页，点击伴读开关。其他网站首次使用需要授权。</li></ol><p>更新手动安装版后需在扩展管理页重新加载并刷新网页。商店安装版在新版本发布后由商店自动更新。</p><p><a href="/api.html">API 配置指南 →</a></p>',True)
write('api.html','API 配置指南', '<p class="eyebrow">BRING YOUR OWN KEY</p><h1>选择服务商，填入自己的密钥。</h1><ol><li>在所选服务商官网开通 API，创建自己的 API Key，确认余额和模型权限。</li><li>打开扩展 → API 设置，选择服务商。密钥、接口地域和模型必须对应。</li><li>默认地址可修改。通常填写以 /v1 等路径结尾的 Base URL，不需要附加 /chat/completions。</li><li>勾选数据与费用说明，点击“测试连接并保存启用”，允许访问此 API 地址。</li><li>成功后回到英文网页阅读。测试也会产生 API 调用。</li></ol><h2>常见服务商</h2><p>千问、DeepSeek、OpenAI、Gemini、Claude、Kimi、GLM、豆包、硅基流动、MiniMax、百度千帆、腾讯混元、Grok、OpenRouter、Groq、Mistral、Together AI、Fireworks AI、Azure OpenAI。另支持 Ollama、LM Studio 和自定义 OpenAI / Anthropic 兼容接口。</p><p>具体模型需以自己账户可用列表为准，不保证所有模型和参数都兼容。模型 ID 可以直接编辑；参数不兼容时可关闭流式或 JSON 模式再测试。</p><h2>费用与隐私</h2><p>伴读不收费，API 费用由你与服务商结算。聊天产品的会员通常不等于 API 额度。密钥仅存本机，正文直接发往所填地址，不经伴读转发。服务商故障不会自动切换到另一家。</p><h2>常见问题</h2><p>401：检查密钥；403：检查地域、模型权限；402：检查余额；404：检查地址及模型 ID；429：等待限额恢复或检查额度。不要把密钥粘贴到问题反馈或截图中。</p><h2>本机模型</h2><p>先在 Ollama 或 LM Studio 启动 API 服务并加载支持中文的模型，再选择对应选项。HTTP 只允许 localhost / 127.0.0.1；远程接口必须使用 HTTPS。</p>',True)
write('privacy.html','隐私政策','<p class="eyebrow">PRIVACY / 2026-09-26</p><h1>隐私政策</h1>'+''.join('<p>'+escape(line)+'</p>' for line in (project/'PRIVACY.md').read_text(encoding='utf-8').splitlines() if line.strip()),True)
write('terms.html','使用说明与条款', '<h1>使用说明与条款</h1><p>伴读由 Nexwave International Limited 维护，以 MIT 许可证提供源码。扩展软件免费，无需伴读账号或付费会员。</p><p>用户负责配置自己的 API 账户、密钥和模型，并遵守所选服务商的条款、配额与费用规则。伴读不提供公共 API 额度，也不代收模型费用。测试、重试和格式修复可能产生多次 API 调用。</p><p>AI 翻译可能不准确，请结合原文。第三方服务、模型或网页结构变化可能影响使用。请仅处理有权访问和提交的内容。EngBetter 是独立可选服务。</p><p>MIT 许可的免责声明见开源仓库。本说明不排除适用法律赋予用户的权利。历史订单及数据申请请联系支持。</p>',True)
write('refunds.html','历史订单与账号', '<h1>历史订单与账号</h1><p>伴读已转为免费、自带 API 的开源扩展，停止新会员购买，不再向新用户提供公共模型额度。</p><p>免费版不使用旧会员账号。历史订单、已付款权益、退款和账号删除请联系 gobacktome123@gmail.com，并提供订单参考号和问题说明。历史付款记录不会因产品改版自动删除；依法需保留的记录另行保留。</p><p>如需查询旧账号，可使用<a href="/account">历史账号入口</a>。此入口仅用于已有记录和过渡服务，不销售新套餐。请勿提供完整银行卡号、密码或 API Key。</p><p>第三方 API 费用由用户与服务商结算，相关退款需联系对应服务商。</p>',True)
write('support.html','帮助与联系', '<h1>需要帮助？</h1><p>安装、API 配置、历史订单与数据删除问题，请联系 '+contact+'</p><p>请提供浏览器版本、扩展版本、服务商名称和错误状态。不要发送 API Key、密码、银行卡号或私人网页全文。</p><p><a href="/install.html">安装说明</a> · <a href="/api.html">API 指南</a> · <a href="https://github.com/polytradingwin/bandu/issues">GitHub Issues</a> · <a href="/refunds.html">历史订单</a></p>', True)
write('about.html','关于伴读','<h1>关于伴读</h1><p>伴读 Bandu 是免费、开源、自带 API 的网页双语阅读扩展。</p><p>维护主体：Nexwave International Limited。</p><p>联系：'+contact+'</p><p>EngBetter 是独立的可选服务；单独使用伴读无需连接。</p>',True)
(root/'robots.txt').write_text('User-agent: *\nAllow: /\nDisallow: /account\nDisallow: /api/\nDisallow: /admin\nSitemap: https://bandume.com/sitemap.xml\n')
(root/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://bandume.com/'+('' if p.name=='index.html' else p.name)+'</loc></url>' for p in sorted(root.glob('*.html')))+'</urlset>')
print('Free website generated')
